### ISSUE TITLE
broken stylesheet in Moodle 3.5

### ISSUE THREAD

**Issue by oORustyOo** [moodleuulm/moodle-local_navbarplus#6]
Hi,

while using Moodle 3.5 the styles.css should be changed/extendet. The `header.navbar` element was changed to `nav.navbar`. (suggestion - see below)

`
/* Float the icons right to be placed next to the existing icons "messages" and "notifications". */
nav.navbar .localnavbarplus.nav-link {
    float: right!important;
    margin-left: 0;
}

/* Increase the padding to the most left existing icon "notifictaions". */
#nav-notification-popover-container {
    margin-left: 10px;
}

/* Do not display the icon if a user has disabled Javascript in his browser. */
body:not(.jsenabled) #local_navbarplus_resetusertour {
    display: none;
}

/* Inherit the colors. */
nav.navbar .localnavbarplus a,
nav.navbar .localnavbarplus .icon {
    color: inherit;
}
`
kind regards
Erik

**Comment by Kathrin84** [comment]
Hi Erik, 
thank you very much for your issue and your improvement proposal. It was sufficient to just remove the header as this was no longer existing in Moodle 3.5.
The new version for 3.5 is finally released in the plugins repository: https://moodle.org/plugins/local_navbarplus.
This issue is fixed and I'll close it.
Best, Kathrin
